#!/bin/bash
# Apply optional IPv6 mode to fail2ban (allowipv6 yes/no).
# Reads /etc/fail2ban/conf.d/ipv6.conf  ENABLE_IPV6=0|1
# Does not restart fail2ban; caller should reload.

set -e
CONF="/etc/fail2ban/conf.d/ipv6.conf"
OUT="/etc/fail2ban/fail2ban.d/allowipv6.conf"
ENABLE_IPV6=0
[ -f "$CONF" ] && . "$CONF"

VAL="no"
[ "${ENABLE_IPV6:-0}" = "1" ] && VAL="yes"

mkdir -p /etc/fail2ban/fail2ban.d
cat > "$OUT" << EOF
# Generated by apply-ipv6-mode.sh — do not edit; use WHM Settings or conf.d/ipv6.conf
[DEFAULT]
allowipv6 = $VAL
EOF

echo "fail2ban allowipv6=$VAL"
