#!/bin/bash
# Generate ONE fail2ban jail for all User-Agent keyword rules.
# One jail (not one per keyword) so we do not poll/watch the same
# 1000+ domlogs six times.
# Reads: /etc/fail2ban/conf.d/useragent-keywords.conf
# Format per line: keyword|maxretry|findtime|bantime

CONFIG="/etc/fail2ban/conf.d/useragent-keywords.conf"
FILTER_DIR="/etc/fail2ban/filter.d"
JAIL_DIR="/etc/fail2ban/jail.d"
LOGPATH="/usr/local/apache/domlogs/*/*"
JAIL_NAME="apache-ua-keywords"

[ ! -f "$CONFIG" ] && {
    rm -f "${JAIL_DIR}"/apache-ua-*.conf "${FILTER_DIR}"/apache-ua-*.conf 2>/dev/null
    fail2ban-client reload 2>/dev/null || true
    exit 0
}

escape_regex() {
    echo "$1" | sed 's/[.[\*^$()+?{|\\]/\\&/g'
}

mkdir -p "$FILTER_DIR" "$JAIL_DIR"

failregex_lines=""
min_retry=""
max_find=""
max_ban=""

while IFS='|' read -r keyword maxretry findtime bantime _; do
    [ -z "$keyword" ] && continue
    keyword=$(echo "$keyword" | tr -d ' ')
    [ -z "$keyword" ] && continue
    maxretry=$(echo "${maxretry:-1}" | tr -cd '0-9')
    findtime=$(echo "${findtime:-60}" | tr -cd '0-9')
    bantime=$(echo "${bantime:-3600}" | tr -cd '0-9')
    [ -z "$maxretry" ] && maxretry=1
    [ -z "$findtime" ] && findtime=60
    [ -z "$bantime" ] && bantime=3600
    maxretry=$((maxretry > 0 ? maxretry : 1))
    findtime=$((findtime > 0 ? findtime : 60))
    bantime=$((bantime > 0 ? bantime : 3600))

    if [ "$keyword" = "_empty_" ]; then
        rx='^<HOST> - .* ".*" [0-9]+ [0-9]+ ".*" "-"$'
    else
        kw_esc=$(escape_regex "$keyword")
        rx="^<HOST> - .* \".*\" [0-9]+ [0-9]+ \".*\" \"(?i).*${kw_esc}.*\""
    fi

    if [ -z "$failregex_lines" ]; then
        failregex_lines="            ${rx}"
        min_retry=$maxretry
        max_find=$findtime
        max_ban=$bantime
    else
        failregex_lines="${failregex_lines}
            ${rx}"
        [ "$maxretry" -lt "$min_retry" ] && min_retry=$maxretry
        [ "$findtime" -gt "$max_find" ] && max_find=$findtime
        [ "$bantime" -gt "$max_ban" ] && max_ban=$bantime
    fi
done < <(grep -v '^#' "$CONFIG" | grep -v '^[[:space:]]*$')

if [ -z "$failregex_lines" ]; then
    rm -f "${JAIL_DIR}"/apache-ua-*.conf "${FILTER_DIR}"/apache-ua-*.conf 2>/dev/null
    fail2ban-client reload 2>/dev/null || true
    exit 0
fi

# First failregex line is assigned; continuation lines stay indented.
failregex_block=$(printf '%s\n' "$failregex_lines" | sed '1s/^            //')

cat > "${FILTER_DIR}/${JAIL_NAME}.conf" << EOF
# Fail2Ban filter: combined User-Agent keyword rules
# Generated by update-useragent-jails.sh (single jail to cut log watches)

[Definition]
failregex = ${failregex_block}
ignoreregex =
datepattern = ^[^\\[]*\\[({DATE})
              {^LN-BEG}
EOF

cat > "${JAIL_DIR}/${JAIL_NAME}.conf" << EOF
# Combined User-Agent keyword jail (generated by update-useragent-jails.sh)
[${JAIL_NAME}]
enabled = true
port = http,https
filter = ${JAIL_NAME}
backend = pyinotify
usedns = no
logpath = ${LOGPATH}
maxretry = ${min_retry}
findtime = ${max_find}
bantime = ${max_ban}
banaction = csf-domain
banaction_allports = csf-domain
EOF

# Remove per-keyword jails/filters left from the old generator
for old in "$FILTER_DIR"/apache-ua-*.conf "${JAIL_DIR}"/apache-ua-*.conf; do
    [ -f "$old" ] || continue
    base=$(basename "$old" .conf)
    [ "$base" = "$JAIL_NAME" ] || rm -f "$old"
done

fail2ban-client reload 2>/dev/null || true
